Correction after dev review
opendata-swiss/ogdch-handbook pull request #100
Opened 2021-06-23 13:14 UTC by sabinem

2021-06-23 17:09 UTC, stefina requested changes

2021-06-23 17:09 UTC, stefina commented on source/content/glossar/bibliothek/dcat-definitions/distribution-rights.rst
> +:Usage Notes: The rights statement is composed of 3 elements that can be merged and summarized as a literal:
I'm still not sure of how much value it is to explain a datapublisher, that the statement consists of three elements. In the end we are only allowing the values we are allowing, listed below,
I'm on the verge of saying that the `Values not acceptable for opendata.swiss` part can be deleted, as every other value is also invalid. But that might be political ¯\_(ツ)_/¯

2021-06-23 17:09 UTC, stefina commented on source/content/glossar/bibliothek/dcat-definitions/distribution-title.rst
> +:Cardinality: 1..4 (one for each language)
before it was 0..n and now it is 1..n. I am certain that you know better, what value needs to be here, but maybe double-check that this is not a typo? 😅

2021-06-23 17:09 UTC, stefina commented on source/content/glossar/bibliothek/dcat-definitions/distribution-title.rst
> +              only the data for one year, where as the dataset covers severel years
... only the data for one year, whereas the dataset covers several years ...

2021-06-23 17:09 UTC, stefina commented on source/content/glossar/bibliothek/dcat-examples/dataset-landing-page-ttl.rst
> +    :caption: The landing page in the current implementation is a string
as the conformancy-aspect is removed from the handbook, I'd try to remove the word current.
`The landing page is a string.`
suffices.

2021-06-23 17:49 UTC, sabinem commented on source/content/glossar/bibliothek/dcat-ap-ch.rst
>      * - :ref:`title <dcat-dataset-title>`
These ref maks really need to stay this way. There are ref-marks for dcat and refmarks for geocat: 
 <dcat-dataset-title> links to the title section on ths dcat page and  <geocat-dataset-title> links to the mapping to the title field on the geocat mapping page,`

2021-06-23 18:13 UTC, stefina commented on source/content/glossar/bibliothek/dcat-ap-ch.rst
>      * - :ref:`title <dcat-dataset-title>`
ahhh, good point, that totally makes sense :) thank you for explaining 🤗

2021-06-24 07:29 UTC, stefina requested changes

2021-06-24 07:29 UTC, stefina commented on source/content/glossar/bibliothek/dcat-definitions/dataset-landing-page.rst
> +              the link should be duplicated as ``dcat:accessURL`` on a distributions.
distribution.

2021-06-24 07:29 UTC, stefina commented on source/content/glossar/bibliothek/dcat-definitions/distribution-rights.rst
> +              non commercial purposes. Does it need be referenced, when it is used? These
Does it need to be ...

2021-06-24 07:29 UTC, stefina commented on source/content/glossar/bibliothek/dcat-definitions/distribution-title.rst
> +              only the data for one year, whereas the dataset covers severel years
several

2021-06-25 08:10 UTC, stefina requested changes

2021-06-25 08:10 UTC, stefina commented on source/content/glossar/bibliothek/dcat-ap-ch.rst
>      * - :ref:`accrual periodicty <dcat-dataset-accrual-periodicity>`
periodicity :)

2021-06-25 11:54 UTC, stefina approved these changes

2021-06-25 12:02 UTC, merged